### ISSUE TITLE
Strategy for managing Windows module

### ISSUE THREAD

**Issue by sabre1041** [wildfly-extras/ansible_collections_jcliff#31]
There has been issues integrating the Windows module into the repository. As discussed between the development team, the following approach will be used to handle Windows support of the jcliff module.

1. Create a new branch dedicated to supporting Windows (`windows_support` or something similar)
2. Remove the windows module from the `master` branch
3. All enhancements to `master` branch should be applied to the Windows branch to ensure feature parity
4. Work with Ansible community and engineering for the best path forward supporting both python and powershell modules

Resolves #23

**Comment by rpelisse** [comment]
Master branch has been reset : https://github.com/wildfly-extras/ansible_collections_jcliff 

Sidenote: I find better to use rebase and commit than merge to keep the history linear. Given when we are right now, I don't think we need branch merge. So I used the opportunity to remove the recent merge of the timeout feature and just let the commit there. 

Feature branch for Windows is here: https://github.com/wildfly-extras/ansible_collections_jcliff/tree/windows_support

This branch will need to be cleaned up and rebase before merging it into master, but we'll cross that bridge when we'll have a proper fix for Windows.
