### ISSUE TITLE
Add variable to enable/disable repo

### ISSUE THREAD

**Issue by dicksol** [wildfly-extras/ansible_collections_jcliff#53]
Seems to be hard coded enabled now:
    - name: "Add JCliff Yum Repository ({{ ansible_distribution}})"
      yum_repository:
        name: jcliff
        description: JCliff repository
        baseurl: "{{ jcliff_yum_baseurl }}"
        gpgcheck: 0

**Comment by rpelisse** [comment]
@dicksol Hi Dick, good point! I've a set up a [PR for this change](https://github.com/wildfly-extras/ansible_collections_jcliff/pull/54), feel free to comment on the implementation and/or vote for the change.

**Comment by dicksol** [comment]
Hi @rpelisse , Thanks for your reply. I was more thinking about a default value via https://github.com/wildfly-extras/ansible_collections_jcliff/blob/master/roles/jcliff/defaults/main.yml wich you can overide in your playbook when needed.

**Comment by rpelisse** [comment]
@dicksol I've change the implementation and added the env_var to the defaults.

**Comment by dicksol** [comment]
Hi @rpelisse , Thanks again. Why not by making use of a variable which enabled/disabled the repo as described here?:
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html

**Comment by rpelisse** [comment]
Oh, why not, indeed? I just assume that if you don't want to enable the repo, you don't want to install it also. I'll rework that right away to support both option (not install at all the repo and install + var to enable/disable the repo)

**Comment by rpelisse** [comment]
Done! Please ignore the CI build errors, they are unrelated.

**Comment by dicksol** [comment]
Approved PR.
