### ISSUE TITLE
Fix typo in the fail message

### ISSUE THREAD

**Issue by cmoulliard** [wildfly-extras/ansible_collections_jcliff#7]
## Issue

Fix bad word used with the fail message `Unsppoorted` to `Unsupported`
See: 
syntax error https://github.com/wildfly-extras/ansible_collections_jcliff/blob/764e9d02a0d7833cc4aa3c1105c1514b746a413c/roles/jcliff/tasks/main.yml#L16

**Comment by rpelisse** [comment]
@cmoulliard can you directly open a PR for this kind of sutff? Thanks !
