### ISSUE TITLE
Improve installation part about jcliff for the different OS

### ISSUE THREAD

**Issue by cmoulliard** [wildfly-extras/ansible_collections_jcliff#8]
## Improvement

As this playbook/role also supports the deployment of jcliff for macos users, then this [chapter](https://github.com/wildfly-extras/ansible_collections_jcliff/blob/80b0bab94a01566726437f4734af2d91290f9592/README.md#ensuring-jcliff-is-available) should be reviewed to : 

- [x] Mention the different os supported
- [x] Specify that homebrew should be installed as prereq for macos users
- [x] Explain how to use/call the jcliff `installation` role

**Comment by rpelisse** [comment]
- [X] Mention the diffrent os supported:

It is already listed in the current documentation : However, currently, this role only supports Linux distribution using Yum (namely Fedora, RHEL and CentOS):

- [X]  Explain how to use/call the jcliff installation role

Also already explained : "For commodity purpose, the Collection comes with a role 'jcliff' to have Ansible install 'jcliff'" (the sentence before). 

(but this one requires a rephrasing, it's not very clear).

I'll update the README anyway, trying to make it more clear and apparent.

**Comment by rpelisse** [comment]
- [X]  Specify that homebrew should be installed as prereq for macosx users

Done: https://github.com/wildfly-extras/ansible_collections_jcliff/pull/9

Please vote and comment on the PR directly.
